import Head from "next/head";
import { Inter } from "@next/font/google";
import { motion as m } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <m.div>
          <div className="relative w-full max-w">
            <div className="flex i">
              <div className="absolute lg:ml-96 lg:mt-24 lg:top-10 lg:left-10 top-0 -left-4 w-72 h-72 bg-pink-300 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>

              <div className="absolute lg:-bottom-8 lg:left-60 -bottom-8 left-20 w-72 h-72 bg-purple-300 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
            </div>
            <div className="relative">
              <div className="flex lg:pl-8 pl-4 lg:ml-40 lg:mt-32 mt-32 lg:pr-0 pr-4 p-1">
                <div>
                  <div className="flex">
                    <h2 className="text-2xl lg:text-6xl font-bold pr-3">
                      Hello
                    </h2>
                    <span className="animate-bounce">
                      <img src="https://img.icons8.com/ios/50/null/so-so.png" />
                    </span>
                  </div>
                  <h1 className="lg:text-7xl text-4xl pt-1 font-light">
                    I&apos;am aryan
                  </h1>
                  <p className="pt-5 text-lg lg:text-2xl font-serif font-light">
                    I&apos;m a Software Engineer based in Toronto. <br />I have
                    a passion for building digital services and Web/Mobile
                    applications. <br />
                    When not working, I love hanging out with my camera and
                    drone. <br />
                    Currently looking for new opportunity.
                  </p>
                  <div className="flex pt-4">
                    <a
                      className="pt-2"
                      href="https://github.com/aryanluther?tab=repositories"
                    >
                      <img src="https://img.icons8.com/ios-glyphs/30/null/github.png" />
                    </a>
                    <a
                      href="https://www.linkedin.com/in/aryan-luthra-2504721a4/"
                      className="p-2"
                    >
                      <img src="https://img.icons8.com/ios-glyphs/30/null/linkedin-2--v1.png" />
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </m.div>
      </main>
    </>
  );
}
